server:
  port: 8085
datasource:
  url: jdbc:h2:mem:solicitudesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: santi
  password: 123
  driver-class-name: org.h2.Driver
jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
springdoc:
  swagger-ui.path: /swagger-ui.html